uberduck-ai/openduck

- clients/simple_bot.py
```
Simple bot that records audio from the microphone, generates an audio response with uberduck or openai, and plays the response.
Usage:
python uberduck_bot.py
Options:
--openai    Use OpenAI for processing instead of Uberduck
Instructions:
0. Set UBERDUCK_API and OPENAI_ORGANIZATION_ID environment variables 
1. Press the space bar to start recording
2. Press the space bar again to stop recording
3. A response will be generated and played
4. Wait for the response to finish playing before starting a new recording
5. Press the space bar to start a new recording
```
Note that there will likely be issues recording/playing audio when working with other hardware. This should be configured as necessary.
> Add simple bot

- openduck-py/observability.py
- openduck-py/openduck_py/db/__init__.py
- openduck-py/openduck_py/routers/voice.py
Also changed the sqlite connection strings to be relative to __file__ so it works outside of docker.
> streamlit app for observing sessions

- openduck-py/observability.py
> checkboxes

- openduck-py/openduck_py/routers/voice.py
Use Whisper tiny.en and log its transcriptions in the streamlit observability.py. Also print the runtime of both Whisper and Fastconformer.
> Whisper comparison

- openduck-py/openduck_py/routers/voice.py
Creates a new async engine on each response task
See https://docs.sqlalchemy.org/en/20/errors.html#error-isce
> Fix asyncio db

- Dockerfile
- docker-compose.yml
- openduck-py/observability.py
- openduck-py/openduck_py/routers/voice.py
* Only download the StyleTTS2 models from S3, not everything in the prototype folder
* Set all observability logs to be shown by default so you don't have to click a bunch of buttons
* Increase timeout to 5 mins so it doesn't close on you during testing
> Some quality of life improvements

- docker-compose.yml
- openduck-py/openduck_py/logging/slack.py
- openduck-py/openduck_py/routers/voice.py
- openduck-py/openduck_py/settings/__init__.py
Also increase the chunk size and use aws s3 sync instead of aws s3 cp in the docker-compose to avoid re-downloading models
> Switch to asyncio.to_thread instead of loop.run_in_executor

- openduck-py/openduck_py/routers/voice.py
Now ResponseAgent has a method receive_audio() which processes a single chunk of audio input, which previously was happening inside the websocket function. This way we can reuse the code between websocket and webRTC
> Matthew refactor response agent

- openduck-py/requirements.txt
pushed this to docker
___
- Removed several dependencies that are no longer used in the project to clean up the `requirements.txt` file.
- This change simplifies the project's dependency tree and potentially reduces the build time and size.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Dependencies</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>requirements.txt</strong><dd><code>Remove Unused Dependencies from Requirements</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
openduck-py/requirements.txt
<li>Removed unused dependencies including <code>Cython</code>, <code>asgiref</code>, <code>asyncpg</code>, …
> Delete some dependencies

- docker-compose.yml
- openduck-py/openduck_py/routers/voice.py
- openduck-py/requirements.txt
Changed the server code so that it runs voice.py as a script, which connects to a Daily call. You can then join the call in your browser and talk to the bot as normal. 
___
- Integrated Daily API for audio processing in the voice router by adding necessary functions and initializing Daily call.
- Updated Docker Compose configuration to run `voice.py` directly and ensure models are synced to the correct directory.
- Added `daily-python` to the project's dependencies to support the new Daily integration.
___
<tr>
<td>
<details>
<summary><strong>voice.py</strong><dd><code>Integrate Daily for Audio Processing in Voice Router</code>&nbsp; &nbsp; &nbsp; &nbsp; …
> Use daily on the server

- openduck-py/openduck_py/routers/voice.py
- Updated the Whisper model used in voice processing from `tiny.en` to `base.en` for potentially improved performance or features.
___
<tr>
<td>
<details>
<summary><strong>voice.py</strong><dd><code>Switch Whisper model to base.en</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
openduck-py/openduck_py/routers/voice.py
- Changed the Whisper model from `tiny.en` to `base.en`.
</details>
</td>
<td><a …
> Switch to whisper base.en

- clients/daily/daily_bot.py
* Connects to the Daily call with the plushy bot
* Uses pyaudio to record the computer mic and play to the speaker mic, just like in simple_bot.py
___
- Implemented a new Daily bot client in Python that connects to a Daily call and handles audio streaming.
- Utilized the PyAudio library to record from the computer's microphone and play audio to the speaker.
- Set up threading to manage audio input and output streams concurrently, ensuring non-blocking operations.
- Configured the Daily API to create virtual microphone and speaker devices with specific sample rates and channels.
- Added a main function to initialize the Daily API, start the audio play thread, and handle graceful shutdown on interrupt.
___
<table><thead><tr><th></th><th align="left">Relevant …
> Daily client

- openduck-py/openduck_py/routers/voice.py
- Added checks in `daily_consumer` and `consumer` functions to prevent sending `None` audio chunks to the `VirtualMicrophoneDevice` and through the `WebSocket`.
- This fix ensures that the application does not attempt to process `None` chunks, which could lead to errors or unexpected behavior.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>voice.py</strong><dd><code>Prevent Sending NoneType Chunks in Voice Routers</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
openduck-py/openduck_py/routers/voice.py
<li>Added a condition to check if the <code>chunk</code> is not <code>None</code> …
> bug fix: Don't send the audio_chunk if it is None

- clients/daily/daily_bot.py
tiny bugfix to allow ctrl-c to kill script.
___
- Introduced a threading event `stop_event` to facilitate a graceful shutdown of the daily bot when a `KeyboardInterrupt` (Ctrl-C) is detected.
- The `play_audio` function now checks `stop_event` to exit the loop, allowing the audio playing thread to terminate properly.
- The `main` function has been updated to set the `stop_event` and re-raise the exception when a `KeyboardInterrupt` occurs, ensuring all threads are signaled to stop.
___
<tr>
<td>
<details>
<summary><strong>daily_bot.py</strong><dd><code>Implement Graceful Shutdown on KeyboardInterrupt</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> stop daily bot on ctrl c

- docker-compose.yml
- openduck-py/observability.py
- openduck-py/openduck_py/models/chat_record.py
- openduck-py/openduck_py/routers/voice.py
Added a "latency" column to DBChatRecord that records the latency of each event. Now streamlit shows
> Log latency in streamlit

- openduck-py/openduck_py/routers/voice.py
We don't need to run speaker diarization because Daily removes echo for us.
___
- Removed the echo removal step from the voice processing pipeline as it is no longer needed due to echo being handled by Daily.
- Simplified the latency logging in the `start_response` function by removing the intermediate time logging for the echo removal step.
___
<tr>
<td>
<details>
<summary><strong>voice.py</strong><dd><code>Remove Echo Removal Processing</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> remove segment audio

- .env.example
- openduck-py/openduck_py/routers/main.py
- openduck-py/openduck_py/routers/ml.py
- openduck-py/openduck_py/routers/voice.py
- openduck-py/openduck_py/settings/__init__.py
- Introduced a new environment variable `ML_API_URL` to configure the machine learning service URL.
- Refactored the main router to dynamically set the `openapi_url` based on the development environment.
- Added a docstring to the `transcribe_audio` function in the ML router for better code documentation.
- Updated voice router to use the `ML_API_URL` variable instead of hardcoded URLs.
- Updated the example environment file `.env.example` to include the new `ML_API_URL` variable.
___
<tr>
<td>
<details>
<summary><strong>main.py</strong><dd><code>Refactor main router and cleanup imports</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> add an ML_API_URL env variable

- openduck-py/openduck_py/routers/voice.py
- web/src/app/page.tsx
- Implemented retry logic in the voice response generation to handle exceptions gracefully by attempting up to 3 retries.
- Enhanced the user interface by adding a microphone toggle feature for the local user with visual feedback using icons.
- Added a spinner component to visually indicate when a user is waiting for others to join the meeting.
- Streamlined the room joining process by removing the room URL input and simplifying the button interactions to create and join a room with a single click.
___
<tr>
<td>
<details>
<summary><strong>voice.py</strong><dd><code>Add retry logic to voice response generation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> improvements

- openduck-py/openduck_py/routers/voice.py
- Lazy loaded `torch` module to prevent performance overhead when creating a new Daily room.
- Ensured `audio_data` is converted to `torch.Tensor` only if necessary, avoiding unnecessary conversions.
- Streamlined audio data processing by removing redundant tensor conversions and directly using numpy arrays.
___
<tr>
<td>
<details>
<summary><strong>voice.py</strong><dd><code>Lazy Load `torch` and Optimize Audio Data Handling</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
openduck-py/openduck_py/routers/voice.py
<li>Lazy import of <code>torch</code> module to improve performance during …
> lazy load torch

- openduck-py/openduck_py/prompts/most-interesting-bot/system-prompt.md
- openduck-py/openduck_py/routers/main.py
- openduck-py/openduck_py/routers/voice.py
- openduck-py/openduck_py/settings/__init__.py
- web/src/app/page.tsx
- Added "https://b898bccd7757.ngrok.app" to the CORS allowed origins to enable cross-origin requests from this new domain.
- Updated the voice router to use the new GPT-4 model (`CHAT_MODEL_GPT4`) and modified the system prompt path to enhance the bot's conversational capabilities.
- Increased the temperature parameter to 1 in the `acompletion` function to allow more creative responses.
- Improved the user interface for joining or leaving a room by changing the element from a div to a button.
- Introduced a new system prompt for the "most-interesting-bot" with guidelines for generating engaging and inquisitive responses during voice calls.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table> …
> [wip] improvements

- openduck-py/openduck_py/prompts/most-interesting-bot/system-prompt.md
- openduck-py/openduck_py/routers/main.py
- openduck-py/openduck_py/routers/voice.py
- openduck-py/openduck_py/settings/__init__.py
- web/src/app/page.tsx
- **improvements**
- **fix required env not in prod**
> zach most interesting bot

- .env.example
- openduck-py/openduck_py/logging/db.py
- openduck-py/openduck_py/response_agent.py
- openduck-py/openduck_py/routers/voice.py
- openduck-py/openduck_py/settings/__init__.py
Just changed the log_event function to upload to S3 using boto3 if a constant is set to True. Was thinking of making a separate Logger class, but I think that's harder since it would have to be instantiated in multiple places. Next we can make a config file to store settings like whether to log to S3.
> Upload logged audio files to S3

- .env.example
- openduck-py/openduck_py/response_agent.py
- openduck-py/openduck_py/settings.py
- openduck-py/openduck_py/utils/daily.py
added the option to transcribe audio with Deepgram. This is non -streaming, just saves the audio np array to a wav file and then sends it to Deepgram to transcribe.
___
- Integrated Deepgram as an alternative ASR method to Whisper.
- Added conditional logic to select between Whisper and Deepgram based on the `ASR_METHOD` setting.
- Created a temporary WAV file for the audio data to be sent to Deepgram for transcription.
- Cleaned up the temporary file after the transcription process is complete.
- Introduced new settings for ASR configuration, including the Deepgram API secret.
- Removed unnecessary print statement for the Daily API key.
- Updated the example environment file with the Deepgram API secret key.
___
<table><thead><tr><th></th><th align="left">Relevant …
> Matthew deepgram

- openduck-py/openduck_py/logging/db.py
- openduck-py/openduck_py/logging/slack.py
- openduck-py/openduck_py/models/chat_history.py
- openduck-py/openduck_py/models/chat_record.py
- openduck-py/openduck_py/prompts/__init__.py
- openduck-py/openduck_py/prompts/intros/greeting.txt
- openduck-py/openduck_py/response_agent.py
- openduck-py/openduck_py/routers/main.py
- openduck-py/openduck_py/routers/voice.py
- openduck-py/openduck_py/utils/daily.py
- openduck-py/openduck_py/utils/third_party_tts.py
- openduck-py/requirements.txt
- web/src/app/page.tsx
___
- Added error handling for Slack API requests and updated model column types for chat history and records.
- Improved interruption handling in the response agent with an event-based mechanism and queue clearing.
- Modified the prompt function to accept prompt names without file extensions.
- Updated CORS configuration and increased chunk size for TTS audio streaming.
- Enhanced voice router endpoints to support interruptions and pass user context to the response agent.
- Updated the daily utility's leave callback to release the client.
- Added a new greeting prompt file for personalized user greetings.
- Updated the web frontend to handle new context data and show loading state when joining a room.
___
<table><thead><tr><th></th><th align="left">Relevant …
> Improve interruption handling

- openduck-py/requirements.txt
- **nice lowkey greeting**
- **Make some progress on interruptions**
- **slightly nicer ui**
- **Improve interruption handling**
- **better recording or partial responses**
- **wip debug logging**
- **Fix slack recording**
- **black**
- **better audio data resets**
- **Fix missed frames bug**
- **add deepgram sdk**
> zach improve conversations

- openduck-py/openduck_py/logging/db.py
- openduck-py/openduck_py/response_agent.py
- openduck-py/openduck_py/routers/voice.py
More accurately measure TTFB latency for LLM and TTS responses.
> Measure LLM and TTS latencies more accurately

- Dockerfile
- The Dockerfile has been updated to manually download and install a specific version of OpenSSL (`libssl1.1_1.1.0g-2ubuntu4_amd64.deb`).
- This ensures that the Docker image uses the intended version of OpenSSL, which may address certain security or compatibility issues.
___
<tr>
<td>
<details>
<summary><strong>Dockerfile</strong><dd><code>Install Specific OpenSSL Version in Dockerfile</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
Dockerfile
<li>Added commands to download and install a specific version of OpenSSL.<br>
</details>
</td>
<td><a …
> Dockerfile OpenSSL fix

- openduck-py/openduck_py/settings.py
- openduck-py/openduck_py/utils/daily.py
- Increased the number of attempts for starting daily recording from 3 to 10 to improve reliability.
- Added a new chat model constant `CHAT_MODEL_GROQ` to the settings.
___
<tr>
<td>
<details>
<summary><strong>settings.py</strong><dd><code>Add New Chat Model Constant</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
openduck-py/openduck_py/settings.py
- Added a new chat model constant `CHAT_MODEL_GROQ`.
</details>
</td>
<td><a …
> increase number of attempts for daily recording

- openduck-py/openduck_py/routers/voice.py
- The TTS (Text-to-Speech) provider in `voice.py` has been switched from Azure to OpenAI.
___
<tr>
<td>
<details>
<summary><strong>voice.py</strong><dd><code>Switch TTS Provider to OpenAI</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
openduck-py/openduck_py/routers/voice.py
- Changed TTS provider from Azure to OpenAI.
</details>
</td>
<td><a href="https://github.com/uberduck-ai/openduck/pull/111/files#diff-83ea5947a09005723a4450b92f794118b9e …
> use openai tts

- openduck-py/openduck_py/prompts/comedy.txt
- openduck-py/openduck_py/routers/ml.py
previously it was crashing if whisper's response["segments"] was an empty list. This was causing some of the no-response errors.
Also have a new comedy prompt generated from Cursor.
___
- Fixed an issue where the application would crash if Whisper's response had no segments by returning an empty string instead.
- Enhanced the comedy prompt to guide the creation of absurdist, Monty Python-esque humor, ensuring a more engaging and whimsical user experience.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>ml.py</strong><dd><code>Handle Empty Segments in Whisper Response</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> Return empty string if whisper returns no segments
